In [7]:
import pandas as pd
import json

In [46]:
def load_data():
    print("Loading Data....")

    customers = pd.read_csv("customers_messy_data.csv")

    import json
    with open("orders.json", "r") as f:
        orders_data = json.load(f)

    orders = pd.DataFrame(orders_data)

    print("Data loaded successfully!")

    return customers, orders

In [47]:
customers = pd.read_csv("customers_messy_data.csv")
customers

,name,age,email,city,salary,review
0,Alice,25.0,alice@email.com,Hyderabad,50000.0,Great service!
1,Bob,NaN,bob@email.com,Mumbai,60000.0,Good but slow delivery
2,Charlie,30.0,NaN,Delhi,70000.0,Bad experience
3,David,22.0,david@email.com,Hyderabad,NaN,Excellent!
4,Eve,29.0,eve@email.com,Bangalore,65000.0,Average service
5,Alice,25.0,alice@email.com,Hyderabad,50000.0,Great service!
6,Frank,35.0,frank@email.com,Chennai,80000.0,Loved it
7,Grace,28.0,grace@email.com,Delhi,72000.0,okay
8,Hannah,31.0,hannah@email.com,Mumbai,68000.0,not satisfied
9,Ibrahim,27.0,NaN,Hyderabad,54000.0,bad
10,John,40.0,john@email.com,Bangalore,90000.0,excellent product
11,Kiran,26.0,kiran@email.com,Chennai,50000.0,nice
12,Latha,NaN,latha@email.com,Delhi,62000.0,good
13,Manoj,33.0,manoj@email.com,NaN,75000.0,awesome
14,Nina,24.0,nina@email.com,Hyderabad,48000.0,fine
15,Omar,29.0,omar@email.com,Mumbai,NaN,slow delivery
16,Priya,32.0,priya@email.com,Bangalore,71000.0,great experience
17,Rahul,28.0,rahul@email.com,Delhi,67000.0,good
18,Sara,27.0,sara@email.com,Chennai,64000.0,bad service
19,Tom,36.0,tom@email.com,Mumbai,82000.0,excellent
20,Uma,30.0,uma@email.com,Hyderabad,69000.0,good service
21,Vikram,34.0,NaN,Bangalore,88000.0,excellent
22,Waseem,31.0,waseem@email.com,Delhi,72000.0,nice experience
23,Xavier,29.0,xavier@email.com,Chennai,66000.0,average
24,Yamini,26.0,yamini@email.com,Hyderabad,55000.0,great
25,Zara,28.0,zara@email.com,Mumbai,60000.0,bad delivery
26,Raj,34.0,raj@email.com,Chennai,79000.0,good
27,Simran,25.0,simran@email.com,Hyderabad,52000.0,nice
28,Akash,32.0,akash@email.com,Mumbai,70000.0,slow service
29,Deepak,36.0,deepak@email.com,Delhi,81000.0,excellent
30,Ritu,27.0,ritu@email.com,Bangalore,61000.0,good
31,Nikhil,29.0,nikhil@email.com,Chennai,67000.0,bad
32,Payal,26.0,payal@email.com,Hyderabad,54000.0,great service
33,Harsha,31.0,harsha@email.com,Mumbai,72000.0,average
34,Kavya,28.0,kavya@email.com,Delhi,65000.0,good
35,Rohan,35.0,rohan@email.com,Bangalore,88000.0,excellent
36,Tanvi,24.0,tanvi@email.com,Chennai,56000.0,nice
37,Ajay,33.0,ajay@email.com,Hyderabad,76000.0,good
38,Shreya,27.0,shreya@email.com,Mumbai,69000.0,great
39,Mohit,30.0,mohit@email.com,Delhi,72000.0,average
40,Isha,25.0,isha@email.com,Bangalore,58000.0,good
41,Kunal,34.0,kunal@email.com,Chennai,80000.0,excellent
42,Rakesh,38.0,rakesh@email.com,Hyderabad,90000.0,great
43,Alice,25.0,alice@email.com,Hyderabad,50000.0,Great service!
44,Bob,NaN,bob@email.com,Mumbai,60000.0,Good but slow delivery

In [10]:
with open("orders.json", "r") as f:
        orders_data = json.load(f)

orders = pd.DataFrame(orders_data)

print("Data loaded successfully!\n")

Data loaded successfully!

In [11]:
print(customers.head())
print("\n")
print(orders.head())

      name   age            email       city   salary                  review
0    Alice  25.0  alice@email.com  Hyderabad  50000.0          Great service!
1      Bob   NaN    bob@email.com     Mumbai  60000.0  Good but slow delivery
2  Charlie  30.0              NaN      Delhi  70000.0          Bad experience
3    David  22.0  david@email.com  Hyderabad      NaN              Excellent!
4      Eve  29.0    eve@email.com  Bangalore  65000.0         Average service


   order_id customer  amount     status
0         1    Alice   250.0  completed
1         2      Bob     NaN    pending
2         3  Charlie   450.0  completed
3         4    Alice   300.0  completed
4         5      Eve   500.0  completed

In [53]:
def clean_customers(customers):
    print("Cleaning customers data...")

    customers = customers.drop_duplicates()
    customers['age'] = customers['age'].fillna(customers['age'].mean())
    customers['salary'] = customers['salary'].fillna(customers['salary'].mean())

    return customers

In [13]:
print("Before:", customers.shape)

print("Duplicates:", customers.duplicated().sum())

customers = customers.drop_duplicates()

print("After:", customers.shape)

Before: (45, 6)
Duplicates: 3
After: (42, 6)

In [14]:
customers['age'].isnull().sum()

np.int64(2)

In [15]:
 customers['age'] = customers['age'].fillna(customers['age'].mean())
 customers['age'].isnull().sum()

C:\Users\shaik\AppData\Local\Temp\ipykernel_29540\872365328.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['age'] = customers['age'].fillna(customers['age'].mean())

np.int64(0)

In [16]:
customers['salary'].isnull().sum()

np.int64(2)

In [17]:
customers['salary'] = customers['salary'].fillna(customers['salary'].median())
customers['salary'].isnull().sum()

C:\Users\shaik\AppData\Local\Temp\ipykernel_29540\2521509777.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['salary'] = customers['salary'].fillna(customers['salary'].median())

np.int64(0)

In [18]:
print("Before:", customers['email'].isnull().sum())

Before: 3

In [19]:
customers = customers.dropna(subset=['email'])

In [20]:
print("After:", customers['email'].isnull().sum())

After: 0

In [21]:
customers['city'].isnull().sum()

np.int64(1)

In [22]:
customers['city']=customers['city'].fillna("unknown")
customers['city'].isnull().sum()

np.int64(0)

In [23]:
print("Customers cleaned!\n")

Customers cleaned!

In [24]:
customers

,name,age,email,city,salary,review
0,Alice,25.00,alice@email.com,Hyderabad,50000.0,Great service!
1,Bob,29.85,bob@email.com,Mumbai,60000.0,Good but slow delivery
3,David,22.00,david@email.com,Hyderabad,68500.0,Excellent!
4,Eve,29.00,eve@email.com,Bangalore,65000.0,Average service
6,Frank,35.00,frank@email.com,Chennai,80000.0,Loved it
7,Grace,28.00,grace@email.com,Delhi,72000.0,okay
8,Hannah,31.00,hannah@email.com,Mumbai,68000.0,not satisfied
10,John,40.00,john@email.com,Bangalore,90000.0,excellent product
11,Kiran,26.00,kiran@email.com,Chennai,50000.0,nice
12,Latha,29.85,latha@email.com,Delhi,62000.0,good
13,Manoj,33.00,manoj@email.com,unknown,75000.0,awesome
14,Nina,24.00,nina@email.com,Hyderabad,48000.0,fine
15,Omar,29.00,omar@email.com,Mumbai,68500.0,slow delivery
16,Priya,32.00,priya@email.com,Bangalore,71000.0,great experience
17,Rahul,28.00,rahul@email.com,Delhi,67000.0,good
18,Sara,27.00,sara@email.com,Chennai,64000.0,bad service
19,Tom,36.00,tom@email.com,Mumbai,82000.0,excellent
20,Uma,30.00,uma@email.com,Hyderabad,69000.0,good service
22,Waseem,31.00,waseem@email.com,Delhi,72000.0,nice experience
23,Xavier,29.00,xavier@email.com,Chennai,66000.0,average
24,Yamini,26.00,yamini@email.com,Hyderabad,55000.0,great
25,Zara,28.00,zara@email.com,Mumbai,60000.0,bad delivery
26,Raj,34.00,raj@email.com,Chennai,79000.0,good
27,Simran,25.00,simran@email.com,Hyderabad,52000.0,nice
28,Akash,32.00,akash@email.com,Mumbai,70000.0,slow service
29,Deepak,36.00,deepak@email.com,Delhi,81000.0,excellent
30,Ritu,27.00,ritu@email.com,Bangalore,61000.0,good
31,Nikhil,29.00,nikhil@email.com,Chennai,67000.0,bad
32,Payal,26.00,payal@email.com,Hyderabad,54000.0,great service
33,Harsha,31.00,harsha@email.com,Mumbai,72000.0,average
34,Kavya,28.00,kavya@email.com,Delhi,65000.0,good
35,Rohan,35.00,rohan@email.com,Bangalore,88000.0,excellent
36,Tanvi,24.00,tanvi@email.com,Chennai,56000.0,nice
37,Ajay,33.00,ajay@email.com,Hyderabad,76000.0,good
38,Shreya,27.00,shreya@email.com,Mumbai,69000.0,great
39,Mohit,30.00,mohit@email.com,Delhi,72000.0,average
40,Isha,25.00,isha@email.com,Bangalore,58000.0,good
41,Kunal,34.00,kunal@email.com,Chennai,80000.0,excellent
42,Rakesh,38.00,rakesh@email.com,Hyderabad,90000.0,great

In [52]:
def clean_orders(orders):
    print("Cleaning orders data...")

    orders = orders[orders['status'] == 'completed']
    orders['amount'] = orders['amount'].fillna(0)

    return orders

In [25]:
def clean_orders(orders):
    print("Cleaning orders data...")

In [26]:
orders['amount'].isnull().sum()

np.int64(2)

In [27]:
orders['amount'] = orders['amount'].fillna(0)
orders['amount'].isnull().sum()

np.int64(0)

In [28]:
print("Before:")
print(orders['status'].value_counts())

orders = orders[orders['status'] == 'completed']

print("\nAfter:")
print(orders['status'].value_counts())

Before:
status
completed    17
pending       2
cancelled     1
Name: count, dtype: int64

After:
status
completed    17
Name: count, dtype: int64

In [29]:
orders['status'].unique()

array(['completed'], dtype=object)

In [30]:

print("Orders cleaned!\n")

Orders cleaned!

In [31]:
 orders

    order_id customer  amount     status
0          1    Alice   250.0  completed
2          3  Charlie   450.0  completed
3          4    Alice   300.0  completed
4          5      Eve   500.0  completed
5          6    Frank   700.0  completed
7          8   Hannah   350.0  completed
8          9     John   900.0  completed
10        11    Latha   400.0  completed
11        12    Manoj   650.0  completed
12        13     Nina   120.0  completed
13        14     Omar     0.0  completed
14        15    Priya   550.0  completed
15        16    Rahul   300.0  completed
16        17     Sara   280.0  completed
17        18      Tom   800.0  completed
18        19      Uma   600.0  completed
19        20     Zara   450.0  completed

In [50]:
print(type(customers))

<class 'pandas.core.frame.DataFrame'>

In [32]:
def process_reviews(customers):
    print("Processing text data...")

    customers['review'] = customers['review'].fillna("").str.lower()

    def sentiment(text):
        if "good" in text or "great" in text or "excellent" in text:
            return "positive"
        elif "bad" in text or "slow" in text:
            return "negative"
        else:
            return "neutral"

    customers['sentiment'] = customers['review'].apply(sentiment)

    print("Text processing done!\n")

    return customers

In [33]:
customers = process_reviews(customers)

Processing text data...
Text processing done!

In [103]:
customers.head()

,name,age,email,city,salary,review,sentiment
0,Alice,25.00,alice@email.com,Hyderabad,50000.0,great service!,positive
1,Bob,29.85,bob@email.com,Mumbai,60000.0,good but slow delivery,positive
3,David,22.00,david@email.com,Hyderabad,68500.0,excellent!,positive
4,Eve,29.00,eve@email.com,Bangalore,65000.0,average service,neutral
6,Frank,35.00,frank@email.com,Chennai,80000.0,loved it,neutral

In [34]:

def aggregate_orders(orders):
    print("Aggregating orders...")

    spending = orders.groupby('customer')['amount'].sum().reset_index()
    spending.columns = ['name', 'total_spent']

    print("Aggregation done!\n")
    return spending

In [35]:
customer_spending = aggregate_orders(orders)

Aggregating orders...
Aggregation done!

In [36]:
customer_spending.head()

      name  total_spent
0    Alice        550.0
1  Charlie        450.0
2      Eve        500.0
3    Frank        700.0
4   Hannah        350.0

In [37]:
def merge_data(customers, spending):
    print("Merging data...")

    final_df = pd.merge(customers, spending, on='name', how='left')

    # Fill customers with no orders
    final_df['total_spent'] = final_df['total_spent'].fillna(0)

    print("Merge complete!\n")
    return final_df

In [38]:
final_df = merge_data(customers, customer_spending)

Merging data...
Merge complete!

In [39]:
final_df.head()

,name,age,email,city,salary,review,sentiment,total_spent
0,Alice,25.00,alice@email.com,Hyderabad,50000.0,great service!,positive,550.0
1,Bob,29.85,bob@email.com,Mumbai,60000.0,good but slow delivery,positive,0.0
2,David,22.00,david@email.com,Hyderabad,68500.0,excellent!,positive,0.0
3,Eve,29.00,eve@email.com,Bangalore,65000.0,average service,neutral,500.0
4,Frank,35.00,frank@email.com,Chennai,80000.0,loved it,neutral,700.0

In [40]:
def save_data(final_df):
    final_df.to_csv("final_output.csv", index=False)
    print("Data saved as final_output.csv\n")

In [41]:
final_df = merge_data(customers, customer_spending)
save_data(final_df)

Merging data...
Merge complete!

Data saved as final_output.csv

In [42]:

def generate_insights(final_df):
    print("Generating insights...\n")

    
    top_customer = final_df.sort_values(by='total_spent', ascending=False).iloc[0]
    print("Top Customer:")
    print(top_customer[['name', 'total_spent']])

    
    revenue_by_city = final_df.groupby('city')['total_spent'].sum()
    print("\nRevenue by City:")
    print(revenue_by_city)

    
    sentiment_count = final_df['sentiment'].value_counts()
    print("\nCustomer Sentiment:")
    print(sentiment_count)

In [43]:
generate_insights(final_df)

Generating insights...

Top Customer:
name            John
total_spent    900.0
Name: 7, dtype: object

Revenue by City:
city
Bangalore    1950.0
Chennai       980.0
Delhi         700.0
Hyderabad    1270.0
Mumbai       1600.0
unknown       650.0
Name: total_spent, dtype: float64

Customer Sentiment:
sentiment
positive    21
neutral     13
negative     5
Name: count, dtype: int64

In [44]:
def run_pipeline():
    customers, orders = load_data()
    customers = clean_customers(customers)
    orders = clean_orders(orders)
    customers = process_reviews(customers)
    spending = aggregate_orders(orders)
    final_df = merge_data(customers, spending)
    save_data(final_df)
    generate_insights(final_df)

In [54]:
run_pipeline()

Loading Data....
Data loaded successfully!
Cleaning customers data...
Cleaning orders data...
Processing text data...
Text processing done!

Aggregating orders...
Aggregation done!

Merging data...
Merge complete!

Data saved as final_output.csv

Generating insights...

Top Customer:
name            John
total_spent    900.0
Name: 9, dtype: object

Revenue by City:
city
Bangalore    1950.0
Chennai       980.0
Delhi        1150.0
Hyderabad    1270.0
Mumbai       1600.0
Name: total_spent, dtype: float64

Customer Sentiment:
sentiment
positive    22
neutral     13
negative     7
Name: count, dtype: int64

C:\Users\shaik\AppData\Local\Temp\ipykernel_29540\3393444436.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['age'] = customers['age'].fillna(customers['age'].mean())
C:\Users\shaik\AppData\Local\Temp\ipykernel_29540\3393444436.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['salary'] = customers['salary'].fillna(customers['salary'].mean())